// <auto-generated />
using Calcados.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Calcados.Migrations
{
    [DbContext(typeof(CalcadoContext))]
    partial class CalcadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Calcados.Models.CalcadoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AlturaCano")
                        .HasColumnType("text");

                    b.Property<decimal>("AlturaSola")
                        .HasColumnType("numeric");

                    b.Property<string>("Cor")
                        .HasColumnType("text");

                    b.Property<string>("Fechamento")
                        .HasColumnType("text");

                    b.Property<string>("Forro")
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnType("text");

                    b.Property<int>("Numeracao")
                        .HasColumnType("integer");

                    b.Property<string>("Palmilha")
                        .HasColumnType("text");

                    b.Property<string>("Solado")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CalcadoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
